# Generated by Django 2.1.2 on 2018-10-26 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_auto_20181024_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendatoin_type', models.CharField(choices=[('CONTENTBASED', 'Content-based'), ('COLLABORATIVE', 'Collaborative'), ('HYBRID', 'Hybrid')], default='CONTENTBASED', max_length=13)),
                ('value', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
