# Generated by Django 2.1.3 on 2018-12-12 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181027_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedmatch',
            name='recommendatoin_type',
            field=models.CharField(choices=[('CONTENTBASED', 'Content-based'), ('COLLABORATIVE', 'Collaborative'), ('RULEBASED', 'Rule-based'), ('HYBRID', 'Hybrid')], default='CONTENTBASED', max_length=13),
        ),
        migrations.AlterField(
            model_name='recommendedmatch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
