# Generated by Django 2.1.1 on 2018-09-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('POSTPONED', 'Postponed'), ('SCHEDULED', 'Scheduled'), ('CANCELED', 'Canceled'), ('SUSPENDED', 'Suspended'), ('IN_PLAY', 'In Play'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('AWARDED', 'Awarded')], default='SCHEDULED', max_length=9)),
                ('match_day', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='website.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='website.Team'),
        ),
    ]
