# Generated by Django 2.1.1 on 2018-10-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
    ]
