# Generated by Django 2.1.1 on 2018-10-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='display_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
