# Generated by Django 2.1.1 on 2018-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_team_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
