# Generated by Django 2.1.2 on 2018-10-24 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181018_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('currentMatchday', models.IntegerField()),
                ('display_name', models.CharField(blank=True, max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='website.Competition')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Match')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='currentSeason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Season'),
        ),
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='website.Competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.Season'),
            preserve_default=False,
        ),
    ]
