# Generated by Django 2.1.2 on 2018-10-27 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20181024_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watches', to=settings.AUTH_USER_MODEL),
        ),
    ]
