# Generated by Django 2.1.2 on 2018-11-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181027_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('nationality', models.CharField(max_length=30)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(choices=[(1, 'Goalkeeper'), (2, 'Defender'), (3, 'Midfielder'), (4, 'Attacker')])),
                ('role', models.IntegerField(choices=[(1, 'Player'), (2, 'Coach'), (3, 'Assistant Coach')])),
                ('influence', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='website.Team')),
            ],
        ),
    ]
