# Generated by Django 2.1.2 on 2018-11-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20181122_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Attacker', 'Attacker')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('PLAYER', 'Player'), ('COACH', 'Coach'), ('ASSISTANT_COACH', 'Assistant Coach')], max_length=15),
        ),
    ]
