# Generated by Django 2.1.3 on 2018-12-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20181209_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_half_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_half_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
