# Generated by Django 2.0.5 on 2018-05-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('le_id', models.AutoField(primary_key=True, serialize=False)),
                ('le_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='MatchSchedule',
            fields=[
                ('ms_id', models.AutoField(primary_key=True, serialize=False)),
                ('ms_time', models.DateTimeField(blank=True, null=True)),
                ('ms_round', models.IntegerField()),
                ('ms_league', models.ForeignKey(db_column='ms_league', on_delete=django.db.models.deletion.DO_NOTHING, to='recommendation.League')),
            ],
            options={
                'db_table': 'match_schedule',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'round',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=50)),
                ('t_shortname', models.CharField(max_length=50)),
                ('t_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='UserWatch',
            fields=[
                ('u_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ms', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recommendation.MatchSchedule')),
            ],
            options={
                'db_table': 'user_watch',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommendation.Team'),
        ),
        migrations.AddField(
            model_name='matchschedule',
            name='ms_team1',
            field=models.ForeignKey(db_column='ms_team1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recommendation.Team'),
        ),
        migrations.AddField(
            model_name='matchschedule',
            name='ms_team2',
            field=models.ForeignKey(db_column='ms_team2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recommendation.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='userwatch',
            unique_together={('u_id', 'ms')},
        ),
    ]
