# Generated by Django 2.0.5 on 2018-07-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_matchprofilevalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchGenerateQueries',
            fields=[
                ('uwg_id', models.AutoField(primary_key=True, serialize=False)),
                ('uwg_query', models.TextField(max_length=1000)),
                ('uwg_description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'user_watch_generate_queries',
            },
        ),
    ]
