# Generated by Django 2.0.5 on 2018-07-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_userwatchgeneratequeries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchgeneratequeries',
            name='uwg_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
