# Generated by Django 2.0.5 on 2018-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_auto_20180703_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchschedule',
            name='ms_team1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchschedule',
            name='ms_team2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
