# Generated by Django 2.0.5 on 2018-07-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20180717_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='t_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recommendation.League'),
        ),
    ]
