# Generated by Django 2.0.5 on 2018-08-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20180717_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchschedule',
            name='ms_season',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
    ]
